### ISSUE TITLE
Once we import the file name, then what?

### ISSUE THREAD

**Issue by trusktr** [aribouius/asset-require-hook#6]
I'm trying to use this in Node.js (electron), and I see a file name is imported. So, then how do we get the file content? Where's the file?

**Comment by aribouius** [comment]
@trusktr the intended usage of this library is to complement the [file-loader](https://github.com/webpack-contrib/file-loader) webpack loader when building server-rendered web apps.  As such, its only purpose is to return the filename (typically a hashed version of it), and not the actual content.

**Comment by trusktr** [comment]
oh okay, thanks!
