### ISSUE TITLE
sorry,but I think there should have "context" option

### ISSUE THREAD

**Issue by tingtingtinghuang** [aribouius/asset-require-hook#7]
Once Webpack set context, the path asset-require-hook generated would be diffrent from url-loader

**Comment by aribouius** [comment]
@huangtting you can use the `publicPath` option to specify the base path.

**Comment by tingtingtinghuang** [comment]
@aribouius Webpack both have publicPath and context. I set publicPath same with Webpack. Do you mean set publicPath same with Webpack'context?

**Comment by VincentCharpentier** [comment]
for some advanced techniques of bundling I'd also need to have some context informations available in a resolver function; Do you think that could be ?
As a workaround I'd like to remove the hook to setup a new one, I'm not sure if that is possible, could you help ?

**Comment by aribouius** [comment]
@tingtingtinghuang yes the `publicPath` option should match what you have in your webpack config.

**Comment by aribouius** [comment]
@VincentCharpentier passing some additional information to the resolver function would be pretty easy to implement, [see here](https://github.com/aribouius/asset-require-hook/blob/master/src/compiler.js#L28).

The library doesn't currently expose an API for removing a hook, but doing so is pretty simple.
```
const addHook = require('asset-require-hook')

addHook({
  extensions: ['jpg']
})

# Removes hook applied above
delete require.extensions['.jpg']
```
